### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by kaneski** [kaneski/vcfmp#1]
- [ ]  Separate Updates from UserProfile models into another relation/class

- [ ] Refactor views on both userprofile and updates app after making changes on userprofile models

- [ ] Refactor Audition views to follow Django's DRY Principle

- [ ] Create Settings view
